import adr01 from "../assets/image/adr01.jpg";
import adr02 from "../assets/image/adr02.jpg";
import p01 from '../assets/image/p01.jpg';
import P2 from '../assets/image/P2.jpg';
import P4 from '../assets/image/P4.jpg';

export const newProducts = [
  {
    id: 1,
    name: "Áo sơ mi nam ",
    price: 10000000,
    brand: "Gucci",
    salePrice: null,
    size: ['S', 'M', 'L', 'XL'],
    alt: "Product 1 Image",
    src: "https://i.imgur.com/7Mt4BkC.jpeg",
    description: 'Sản phẩm được nhiều người yêu thích',
    images: [
      "https://i.imgur.com/7Mt4BkC.jpeg",
      p01
    ],
    rating: 4.8,
    isNew: true
  },
  {
    id: 2,
    name: "Quần jean nam",
    price: 199999999,
    brand: "Gucci",
    salePrice: null,
    size: ['S', 'M', 'L', 'XL'],
    alt: "Product 2 Image",
    src: adr01,
    description: 'Sản phẩm được nhiều người yêu thích',
    rating: 4.5,
    isNew: true
  },
  {
    id: 3,
    name: "Áo khoác nam ",
    price: 119999999,
    brand: "Gucci",
    salePrice: null,
    size: ['S', 'M', 'L', 'XL'],
    alt: "Product 3 Image",
    src: "https://i.imgur.com/7Mt4BkC.jpeg",
    description: 'Sản phẩm được nhiều người yêu thích',
    rating: 4.2,
    isNew: true
  },
  {
    id: 4,
    name: "Áo thun nam ",
    price: 199999999,
    brand: "Gucci",
    salePrice: null,
    size: ['S', 'M', 'L', 'XL'],
    alt: "Product 4 Image",
    src: adr01,
    description: 'Sản phẩm được nhiều người yêu thích',
    rating: 4.7,
    isNew: true
  },
  {
    id: 5,
    name: "Quần Tây Nam size M mới nhất",
    price: 199999999,
    brand: "Gucci",
    salePrice: null,
    size: ['S', 'M', 'L', 'XL'],
    alt: "Product 5 Image",
    src: "https://i.imgur.com/7Mt4BkC.jpeg",
    description: 'Sản phẩm được nhiều người yêu thích',
    rating: 4.6,
    isNew: true
  },
  {
    id: 6,
    name: "Quần Tây Nam size M mới nhất",
    price: 199999999,
    brand: "Gucci",
    salePrice: null,
    size: ['S', 'M', 'L', 'XL'],
    alt: "Product 5 Image",
    src: "https://i.imgur.com/7Mt4BkC.jpeg",
    description: 'Sản phẩm được nhiều người yêu thích',
    rating: 4.6,
    isNew: true
  },
  {
    id: 7,
    name: "Quần Tây Nam size M mới nhất",
    price: 199999999,
    brand: "Gucci",
    salePrice: null,
    size: ['S', 'M', 'L', 'XL'],
    alt: "Product 5 Image",
    src: "https://i.imgur.com/7Mt4BkC.jpeg",
    description: 'Sản phẩm được nhiều người yêu thích',
    rating: 4.6,
    isNew: true
  },
  {
    id: 8,
    name: "Quần Tây Nam size M mới nhất",
    price: 199999999,
    brand: "Gucci",
    salePrice: null,
    size: ['S', 'M', 'L', 'XL'],
    alt: "Product 5 Image",
    src: "https://i.imgur.com/7Mt4BkC.jpeg",
    description: 'Sản phẩm được nhiều người yêu thích',
    rating: 4.6,
    isNew: true
  },
  {
    id: 9,
    name: "Quần Tây Nam size M mới nhất",
    price: 199999999,
    brand: "Gucci",
    salePrice: null,
    size: ['S', 'M', 'L', 'XL'],
    alt: "Product 5 Image",
    src: "https://i.imgur.com/7Mt4BkC.jpeg",
    description: 'Sản phẩm được nhiều người yêu thích',
    rating: 4.6,
    isNew: true
  },
  {
    id: 10,
    name: "Quần Tây Nam size M mới nhất",
    price: 199999999,
    brand: "Gucci",
    salePrice: null,
    size: ['S', 'M', 'L', 'XL'],
    alt: "Product 5 Image",
    src: "https://i.imgur.com/7Mt4BkC.jpeg",
    description: 'Sản phẩm được nhiều người yêu thích',
    rating: 4.6,
    isNew: true
  },
  
  
];

export const bestsellerProducts = [
  {
    id: 1,
    name: "Product 1",
    price: 19999999,
    brand: "Gucci",
    salePrice: 18900000,
    size: ['S', 'M', 'L', 'XL'],
    alt: "Product 1 Image",
    src: "https://i.imgur.com/7Mt4BkC.jpeg",
    description: 'Sản phẩm được nhiều người yêu thích',
    rating: 4.9,
    isNew: false
  },
  {
    id: 2,
    name: "Product 2",
    price: 19999900,
    brand: "Gucci",
    salePrice: null,
    size: ['S', 'M', 'L', 'XL'],
    alt: "Product 2 Image",
    src: adr02,
    description: 'Sản phẩm được nhiều người yêu thích',
    rating: 4.4,
    isNew: false
  },
  {
    id: 3,
    name: "Product 1",
    price: 19999999,
    brand: "Gucci",
    salePrice: 19990000,
    size: ['S', 'M', 'L', 'XL'],
    alt: "Product 1 Image",
    src: "https://i.imgur.com/7Mt4BkC.jpeg",
    description: 'Sản phẩm được nhiều người yêu thích',
    rating: 4.9,
    isNew: false
  },
  {
    id: 4,
    name: "Product 2",
    price: 19999999,
    brand: "Gucci",
    salePrice: 1878788,
    size: ['S', 'M', 'L', 'XL'],
    alt: "Product 2 Image",
    src: adr02,
    description: 'Sản phẩm được nhiều người yêu thích',
    rating: 4.4,
    isNew: false
  },
  {
    id: 5,
    name: "Product 1",
    price: 19999999,
    brand: "Gucci",
    salePrice: 1923456,
    size: ['S', 'M', 'L', 'XL'],
    alt: "Product 1 Image",
    src: "https://i.imgur.com/7Mt4BkC.jpeg",
    description: 'Sản phẩm được nhiều người yêu thích',
    rating: 4.9,
    isNew: false
  },
  {
    id: 6,
    name: "Product 2",
    price: 19999999,
    brand: "Gucci", 
    salePrice: 1876540,
    size: ['S', 'M', 'L', 'XL'],
    alt: "Product 2 Image",
    src: adr02,
    description: 'Sản phẩm được nhiều người yêu thích',
    rating: 4.4,
    isNew: false
  },
  {
    id: 7,
    name: "Product 1",
    price: 19999999,
    brand: "Gucci",
    salePrice: 1467688,
    size: ['S', 'M', 'L', 'XL'],
    alt: "Product 1 Image",
    src: "https://i.imgur.com/7Mt4BkC.jpeg",
    description: 'Sản phẩm được nhiều người yêu thích',
    rating: 4.9,
    isNew: false
  },
  {
    id: 8,
    name: "Product 2",
    price: 19999999,
    brand: "Gucci",
    salePrice: 1545454,
    size: ['S', 'M', 'L', 'XL'],
    alt: "Product 2 Image",
    src: adr02,
    description: 'Sản phẩm được nhiều người yêu thích',
    rating: 4.4,
    isNew: false
  },
  {
    id: 9,
    name: "Product 1",
    price: 19999999,
    brand: "Gucci",
    salePrice: 1554647,
    size: ['S', 'M', 'L', 'XL'],
    alt: "Product 1 Image",
    src: "https://i.imgur.com/7Mt4BkC.jpeg",
    description: 'Sản phẩm được nhiều người yêu thích',
    rating: 4.9,
    isNew: false
  },
  {
    id: 10,
    name: "Product 2",
    price: 19999999,
    brand: "Gucci",
    salePrice: 1676558,
    size: ['S', 'M', 'L', 'XL'],
    alt: "Product 2 Image",
    src: adr02,
    description: 'Sản phẩm được nhiều người yêu thích',
    rating: 4.4,
    isNew: false
  },
  {
    id: 9,
    name: "Product 1",
    price: 19999999,
    brand: "Gucci",
    salePrice: 1636589,
    size: ['S', 'M', 'L', 'XL'],
    alt: "Product 1 Image",
    src: "https://i.imgur.com/7Mt4BkC.jpeg",
    description: 'Sản phẩm được nhiều người yêu thích',
    rating: 4.9,
    isNew: false
  },
  {
    id: 10,
    name: "Product 2",
    price: 19999999,
    brand: "Gucci",
    salePrice: 1234567,
    size: ['S', 'M', 'L', 'XL'],
    alt: "Product 2 Image",
    src: adr02,
    description: 'Sản phẩm được nhiều người yêu thích',
    rating: 4.4,
    isNew: false
  },
];

export const saleproducts = [
  {
    id: 8,
    name: "Product 1",
    price: 19999999,
    brand: "Gucci",
    salePrice: 1234567,
    size: ['S', 'M', 'L', 'XL'],
    alt: "Product 1 Image",
    src: "https://i.imgur.com/7Mt4BkC.jpeg",
    description: 'Sản phẩm được nhiều người yêu thích',
    rating: 4.1,
    isNew: false
  },
  {
    id: 9,
    name: "Product 2",
    price: 19999999,
    brand: "Gucci",
    salePrice: 1234567,
    size: ['S', 'M', 'L', 'XL'],
    alt: "Product 2 Image",
    src: p01,
    rating: 4.3,
    isNew: false
  },
  {
    id: 8,
    name: "Product 1",
    price: 19999999,
    brand: "Gucci",
    salePrice: 1234567,
    size: ['S', 'M', 'L', 'XL'],
    alt: "Product 1 Image",
    src: "https://i.imgur.com/7Mt4BkC.jpeg",
    description: 'Sản phẩm được nhiều người yêu thích',
    rating: 4.1,
    isNew: false
  },
  {
    id: 9,
    name: "Product 2",
    price: 19999999,
    brand: "Gucci",
    salePrice: 1234567,
    size: ['S', 'M', 'L', 'XL'],
    alt: "Product 2 Image",
    src: p01,
    rating: 4.3,
    isNew: false
  },
  {
    id: 8,
    name: "Product 1",
    price: 19999999,
    brand: "Gucci",
    salePrice: 1234567,
    size: ['S', 'M', 'L', 'XL'],
    alt: "Product 1 Image",
    src: "https://i.imgur.com/7Mt4BkC.jpeg",
    description: 'Sản phẩm được nhiều người yêu thích',
    rating: 4.1,
    isNew: false
  },
  {
    id: 9,
    name: "Product 2",
    price: 19999999,
    brand: "Gucci",
    salePrice: 1234567,
    size: ['S', 'M', 'L', 'XL'],
    alt: "Product 2 Image",
    src: p01,
    rating: 4.3,
    isNew: false
  },
  {
    id: 8,
    name: "Product 1",
    price: 19999999,
    brand: "Gucci",
    salePrice: 1234567,
    size: ['S', 'M', 'L', 'XL'],
    alt: "Product 1 Image",
    src: "https://i.imgur.com/7Mt4BkC.jpeg",
    description: 'Sản phẩm được nhiều người yêu thích',
    rating: 4.1,
    isNew: false
  },
  {
    id: 9,
    name: "Product 2",
    price: 19999999,
    brand: "Gucci",
    salePrice: 1234567,
    size: ['S', 'M', 'L', 'XL'],
    alt: "Product 2 Image",
    src: p01,
    rating: 4.3,
    isNew: false
  },
  {
    id: 8,
    name: "Product 1",
    price: 19999999,
    brand: "Gucci",
    salePrice: 1234567,
    size: ['S', 'M', 'L', 'XL'],
    alt: "Product 1 Image",
    src: "https://i.imgur.com/7Mt4BkC.jpeg",
    description: 'Sản phẩm được nhiều người yêu thích',
    rating: 4.1,
    isNew: false
  },
  {
    id: 9,
    name: "Product 2",
    price: 19999999,
    brand: "Gucci",
    salePrice: 1234567,
    size: ['S', 'M', 'L', 'XL'],
    alt: "Product 2 Image",
    src: p01,
    rating: 4.3,
    isNew: false
  },
  {
    id: 8,
    name: "Product 1",
    price: 19999999,
    brand: "Gucci",
    salePrice: 1234567,
    size: ['S', 'M', 'L', 'XL'],
    alt: "Product 1 Image",
    src: "https://i.imgur.com/7Mt4BkC.jpeg",
    description: 'Sản phẩm được nhiều người yêu thích',
    rating: 4.1,
    isNew: false
  },
  {
    id: 9,
    name: "Product 2",
    price: 19999999,
    brand: "Gucci",
    salePrice: 1234567,
    size: ['S', 'M', 'L', 'XL'],
    alt: "Product 2 Image",
    src: p01,
    rating: 4.3,
    isNew: false
  },
];

export const relatedProducts = [
  {
    id: 10,
    name: "Cool T-Shirt",
    alt: "Product 1 Image",
    brand: "Gucci",
    salePrice: 1234567,
    size: ['S', 'M', 'L', 'XL'],
    price: 209999999,
    src: P4,
    rating: 4.6,
    isNew: false
  },
  {
    id: 11,
    name: "Comfy Jeans",
    alt: "Product 1 Image",
    price: 209999999,
    brand: "Gucci",
    salePrice: 1234567,
    size: ['S', 'M', 'L', 'XL'],
    src: P2,
    rating: 4.7,
    isNew: false
  },
  {
    id: 12,
    name: "Cool T-Shirt",
    alt: "Product 1 Image",
    price: 209999999,
    brand: "Gucci",
    salePrice: 1234567,
    size: ['S', 'M', 'L', 'XL'],
    src: P4,
    rating: 4.2,
    isNew: false
  },
  {
    id: 13,
    name: "Comfy Jeans",
    alt: "Product 1 Image",
    price: 209999999,
    brand: "Gucci",
    salePrice: 1234567,
    size: ['S', 'M', 'L', 'XL'],
    src: P2,
    rating: 4.8,
    isNew: false
  },
  {
    id: 14,
    name: "Cool T-Shirt",
    alt: "Product 1 Image",
    price: 209999999,
    brand: "Gucci",
    salePrice: 1234567,
    size: ['S', 'M', 'L', 'XL'],
    src: P4,
    rating: 4.3,
    isNew: false
  },
  {
    id: 15,
    name: "Comfy Jeans",
    alt: "Product 1 Image",
    price: 209999999,
    brand: "Gucci",
    salePrice: 1234567,
    size: ['S', 'M', 'L', 'XL'],
    src: P4,
    rating: 4.5,
    isNew: false
  },
  {
    id: 16,
    name: "Cool T-Shirt",
    alt: "Product 1 Image",
    price: 209999999,
    brand: "Gucci",
    salePrice: 1234567,
    size: ['S', 'M', 'L', 'XL'],
    src: P2,
    rating: 4.6,
    isNew: false
  },
  {
    id: 17,
    name: "Comfy Jeans",
    alt: "Product 1 Image",
    price: 209999999,
    brand: "Gucci",
    salePrice: 1234567,
    size: ['S', 'M', 'L', 'XL'],
    src: P2,
    rating: 4.7,
    isNew: false
  },
];

const allProducts = [
  ...newProducts,
  ...bestsellerProducts,
  ...saleproducts,
  ...relatedProducts
];

const uniqueProducts = Array.from(
  new Map(allProducts.map((product) => [product.id, product])).values()
);

export { uniqueProducts };

// import adr01 from "../assets/image/adr01.jpg";
// import adr02 from "../assets/image/adr02.jpg";
// import p01 from '../assets/image/p01.jpg';
// import P2 from '../assets/image/P2.jpg';
// import P4 from '../assets/image/P4.jpg';

// const allProducts = [
//   {
//     id: 1,
//     name: "Áo sơ mi nam cao cấp",
//     price: 1200000,
//     brand: "Gucci",
//     salePrice: null,
//     size: ['S', 'M', 'L', 'XL'],
//     color: ['trắng', 'xanh'],
//     alt: "Áo sơ mi nam",
//     src: "https://i.imgur.com/7Mt4BkC.jpeg",
//     description: 'Áo sơ mi chất liệu cotton mềm mại, thoáng khí',
//     images: [
//       "https://i.imgur.com/7Mt4BkC.jpeg",
//       p01
//     ],
//     rating: 4.8,
//     reviewCount: 128,
//     isNew: true,
//     isBestseller: false,
//     category: 'shirt',
//     tags: ['formal', 'office'],
//     createdAt: '2023-10-15',
//     stock: 50
//   },
//   {
//     id: 2,
//     name: "Quần jean nam slim fit",
//     price: 1500000,
//     brand: "Levi's",
//     salePrice: 1300000,
//     size: ['28', '30', '32', '34'],
//     color: ['xanh đậm', 'đen'],
//     alt: "Quần jean nam",
//     src: adr01,
//     description: 'Quần jean co giãn 4 chiều, thoải mái vận động',
//     rating: 4.5,
//     reviewCount: 89,
//     isNew: true,
//     isBestseller: true,
//     category: 'pants',
//     tags: ['casual', 'trendy'],
//     createdAt: '2023-10-10',
//     stock: 35
//   },
//   {
//     id: 3,
//     name: "Áo khoác dù nam",
//     price: 850000,
//     brand: "Uniqlo",
//     salePrice: 750000,
//     size: ['M', 'L', 'XL'],
//     color: ['đen', 'xám'],
//     alt: "Áo khoác dù",
//     src: adr02,
//     description: 'Áo khoác chống nước nhẹ, tiện dụng',
//     rating: 4.6,
//     reviewCount: 64,
//     isNew: false,
//     isBestseller: true,
//     category: 'jacket',
//     tags: ['outdoor', 'waterproof'],
//     createdAt: '2023-09-20',
//     stock: 28
//   },
//   {
//     id: 4,
//     name: "Áo thun cổ tròn",
//     price: 350000,
//     brand: "Cotton On",
//     salePrice: null,
//     size: ['S', 'M', 'L'],
//     color: ['trắng', 'đen', 'xám'],
//     alt: "Áo thun nam",
//     src: P2,
//     description: 'Áo thun cotton 100%, thấm hút tốt',
//     rating: 4.3,
//     reviewCount: 112,
//     isNew: false,
//     isBestseller: true,
//     category: 't-shirt',
//     tags: ['basic', 'comfort'],
//     createdAt: '2023-08-15',
//     stock: 72
//   },
//   {
//     id: 5,
//     name: "Quần âu nam cao cấp",
//     price: 980000,
//     brand: "Zara",
//     salePrice: 880000,
//     size: ['28', '30', '32'],
//     color: ['đen', 'xám đậm'],
//     alt: "Quần âu nam",
//     src: P4,
//     description: 'Quần âu không nhăn, form slim fit',
//     rating: 4.7,
//     reviewCount: 56,
//     isNew: true,
//     isBestseller: false,
//     category: 'pants',
//     tags: ['formal', 'office'],
//     createdAt: '2023-10-05',
//     stock: 42
//   },
//   {
//     id: 6,
//     name: "Giày thể thao nam",
//     price: 1200000,
//     brand: "Nike",
//     salePrice: 1100000,
//     size: ['38', '39', '40', '41'],
//     color: ['trắng', 'đen'],
//     alt: "Giày thể thao",
//     src: "https://i.imgur.com/sneaker-image.jpg",
//     description: 'Giày chạy bộ đế êm, nhẹ',
//     rating: 4.9,
//     reviewCount: 203,
//     isNew: false,
//     isBestseller: true,
//     category: 'shoes',
//     tags: ['sport', 'running'],
//     createdAt: '2023-07-22',
//     stock: 19
//   },
//   {
//     id: 7,
//     name: "Túi đeo chéo nam",
//     price: 650000,
//     brand: "H&M",
//     salePrice: null,
//     size: ['One Size'],
//     color: ['đen', 'nâu'],
//     alt: "Túi đeo chéo",
//     src: "https://i.imgur.com/bag-image.jpg",
//     description: 'Túi đeo chéo đa năng, nhiều ngăn',
//     rating: 4.4,
//     reviewCount: 47,
//     isNew: true,
//     isBestseller: false,
//     category: 'accessory',
//     tags: ['streetwear', 'utility'],
//     createdAt: '2023-10-12',
//     stock: 31
//   },
//   {
//     id: 8,
//     name: "Áo len nam cổ lọ",
//     price: 720000,
//     brand: "Mango",
//     salePrice: 680000,
//     size: ['S', 'M', 'L'],
//     color: ['xanh navy', 'xám'],
//     alt: "Áo len nam",
//     src: "https://i.imgur.com/sweater-image.jpg",
//     description: 'Áo len mềm mại, giữ ấm tốt',
//     rating: 4.6,
//     reviewCount: 38,
//     isNew: false,
//     isBestseller: false,
//     category: 'sweater',
//     tags: ['winter', 'warm'],
//     createdAt: '2023-09-05',
//     stock: 24
//   },
//   {
//     id: 9,
//     name: "Quần short nam thể thao",
//     price: 420000,
//     brand: "Adidas",
//     salePrice: 390000,
//     size: ['S', 'M', 'L'],
//     color: ['xanh', 'đen'],
//     alt: "Quần short",
//     src: "https://i.imgur.com/shorts-image.jpg",
//     description: 'Quần thể thao thoáng khí, nhanh khô',
//     rating: 4.5,
//     reviewCount: 76,
//     isNew: false,
//     isBestseller: true,
//     category: 'shorts',
//     tags: ['sport', 'gym'],
//     createdAt: '2023-08-30',
//     stock: 53
//   },
//   {
//     id: 10,
//     name: "Áo hoodie nam",
//     price: 890000,
//     brand: "Puma",
//     salePrice: null,
//     size: ['M', 'L', 'XL'],
//     color: ['đen', 'xám'],
//     alt: "Áo hoodie",
//     src: "https://i.imgur.com/hoodie-image.jpg",
//     description: 'Áo hoodie chất liệu nỉ mềm, có mũ',
//     rating: 4.7,
//     reviewCount: 92,
//     isNew: true,
//     isBestseller: true,
//     category: 'hoodie',
//     tags: ['casual', 'streetwear'],
//     createdAt: '2023-10-08',
//     stock: 41
//   }
// ];

// export default allProducts;